### ISSUE TITLE
作業時間の確保

### ISSUE THREAD

**Issue by amderbar** [rodbb/lambic#1]
メンバーが集まってMTGなり作業なりする時間が取りにくい。
やるとするなら以下が候補。

* サークル活動時間
* もくもく勉強会
* その他業務後
* 休日に集まる

上３つは残業があるとできない。

**Comment by amderbar** [comment]
休日に集まるとしたら場所選びも問題。
必要な条件は以下の通り。

* 電源が使えること
* Wi-Fiが使えること
* 多少騒いでもよいこと
* ホワイトボードがあるとなお良い

この条件を満たしそうなもの。

* 貸し会議室
* 図書館のコモンスペース
* コーヒーショップ
* ~~メンバー自宅~~

**Comment by amderbar** [comment]
2018年12月30日にコーヒーショップでMTGを実施。
その後は各人で作業を進めることに。

**Comment by amderbar** [comment]
やっぱなかなか時間取れない。どうしよう？

**Comment by Y-Kanoh** [comment]
ちょっとずつは進めているが...やはりまとまった時間が欲しい。
特に、作業時間が確保できないのは仕方ないとしても、定期的に合意形成の場を作る必要はありそう。

とりあえず再び候補を挙げてみる。

1. もくもく勉強会の活用
2. サークル活動時間 → 他サークル活動と被ってる
3. なんでもない業務後 → ~~脱 残業~~
4. ランチミーテイング （会議室とか取っちゃう？）
5. 睡眠時間を削る
