### ISSUE TITLE
スタンプカウントの非表示について

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#101]
# 概要

stampドキュメントの`canUse`がfalseの場合、カウント数が表示されない。
後から見返すことを考えると、表示しておいた方がよいと思う。

![image](https://user-images.githubusercontent.com/12679843/58382594-28d9ce80-8007-11e9-9028-e858c2a8b27c.png)

**Comment by skaji18** [comment]
おそらくstampCountsのドキュメントがない場合は空文字列が表示されるようにしているので、それが原因かと思います。
で、このドキュメントがない状態が基本的にはあり得ない前提で作っていたので、このように表示されてしまっています。

> 後から見返すことを考えると

これはどういったケースなのでしょうか？  
最初からずっとそのスタンプが使えない状態であれば、そもそもスタンプを押せないようにして対応するほうが良いと思います。  
また、途中までスタンプが使える状態だったけど、どこかのタイミングから使えなくする場合は、`ドキュメントは存在する`ため、何かしらの数値が表示されるはずです。

以上のことを踏まえて、そもそもstampが使えないケースがどんなケースなのかを分類してから考えたいです。上で挙げたケースでは
* 最初からずっと使えない
* 最初は使えるが途中から使えなくなる

※上記2つの状態を同じシールドで管理するのは避けたいです。  
スタンプを表示しない・スタンプを表示するが押せない、という画面表示内容が異なってくるので。。
