### ISSUE TITLE
コメント機能の強化

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#103]
# 概要
コメント機能について、以下のように必要な機能を追加する。

* 編集機能
* 削除機能
* URLをリンクにする

**Comment by skaji18** [comment]
> URLをリンクにする

URLとしてのパースが大変。
* 日本語を許容するか
* URLとその他文字列との区別はどう判定するか

**Comment by skaji18** [comment]
URLだけ別に切り出さないと、編集・削除がいつまでたってもマージされなさそう。

**Comment by amderbar** [comment]
> URLをリンクにする

別issueにしました #118 。いったん編集・削除を対象にします。
