### ISSUE TITLE
リリースノート作成

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#104]
# 概要
Lambic の新機能を毎回プレゼンするわけにはいかないので、
リリースノートを作成したい。

**Comment by skaji18** [comment]
わかりやすいように、以下のようなカテゴリで管理したいですね
* 新機能
* バグ修正
* その他（パフォーマンス改善など）

あとはリリースごとに何の対応をしたのか、バージョンごとの管理も必要そう。  
そういえば`Lambic`のバージョンは特に決まっていないですね
