### ISSUE TITLE
タップなしにコメントを入力

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#108]
コメント入力時、フローティングボタンを押してから、入力欄をタップしないと入力できない。

タップせずに入力できるほうが、動作が少なく、発表を聞きながらのコメント投稿がやりやすい。

<img src="https://user-images.githubusercontent.com/12679843/58549076-ac80fe80-8245-11e9-9e73-5777dd4a77ef.jpeg" width="200px">

**Comment by amderbar** [comment]
`textarea`には`autofocus`属性がすでにつけられていてそれが聞いていないっぽい。
解決策はぱっとは分からなかった。思っていたよりも厄介そう。

**Comment by skaji18** [comment]
> textareaにはautofocus属性がすでにつけられていてそれが聞いていないっぽい。

動きを見ているに`初回表示時`のみ聞いているようです。  
それを踏まえたうえでの解決策が示されており、dialogの表示・非表示に合わせてtextareaの表示・非表示も切り替えて、うまく`初回表示時`の状態をつくるようです。  
https://stackoverflow.com/questions/51472947/vuetifys-autofocus-works-only-on-first-modal-open#answer-51476992
