### ISSUE TITLE
コメント機能の強化（削除コメントのメッセージ）

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#120]
# 概要

削除したコメントは、「このコメントは削除されました。」と表示したい。

# 目的・背景

削除されたことはログとして残しておいた方が、以下のような場合にありがたい。

* 投稿したつもりのコメントが存在しない場合に、削除されたのか投稿し損ねていたのかわかりやすい。
* 削除されたコメントがわかることで、前後コメントの脈絡が合わなくても内容を察することができる。

# 提案内容

削除されたコメントは「このコメントは削除されました。」と表示し、元の場所に表示する。

**Comment by amderbar** [comment]
削除されたあと、ずっと「削除されました」と表示し続ける？
リロード等したらもう表示もしないという仕様もありなのでは。

**Comment by Y-Kanoh** [comment]
こういう状態もあるのかなと。
一応誰かが発言していたことは残しておいた方が使い勝手が良くない？？

![image](https://user-images.githubusercontent.com/12679843/59972891-15079500-95d2-11e9-99a8-68ec42fe3a3f.png)

**Comment by Y-Kanoh** [comment]
FYI:LINEの場合

![7F35BEBB-257D-46F6-8CF8-F98B3A189006](https://user-images.githubusercontent.com/12679843/59972932-b989d700-95d2-11e9-9663-469157032252.jpeg)

**Comment by Y-Kanoh** [comment]
話し合いによって、なしでいいんじゃないかとなったので、クローズ。
