### ISSUE TITLE
FB促進機能(プライベートコメント)

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#126]
# 概要
全体に公開されているコメントでは、発表へのアドバイスや指摘を投稿しづらいため、発表へのフィードバック(FB)が少なくなってしまう。
そこで、発表者と投稿者のみが閲覧できるコメント機能を追加する。

# 目的・背景
現在のコメント機能は、全員に公開されているため、投稿者は発表の指摘や問題点を全員の前で指摘しづらい。
そのため、本アプリの目的の一つである発表へのFBが少なくなってしまう懸念がある。

# 提案内容
発表者と投稿者のみが閲覧できる「プライベートコメント」を投稿できるようにする。

## メリット
* 第三者に閲覧されないため、率直なFBが投稿できる
* 第三者に閲覧されないため、指摘される側の心理的負担が減少される

## デメリット/懸念点
* プライベートコメントでマサカリが多数発生する

**Comment by Y-Kanoh** [comment]
# 仕様案

## Spec1. コメント投稿画面の実装
<img src="https://user-images.githubusercontent.com/12679843/60751667-7416d200-9ff4-11e9-89a4-bee528e7bf13.png" width="200">

* チェックボックスで選択
* チェックONでプライベートコメント
* プライベートコメントの説明がないので、[toolchip](https://vuetifyjs.com/ja/components/tooltips)をdどこかにつけたい


## Spec2. プライベートコメント表示

<img src="https://user-images.githubusercontent.com/12679843/60751678-c7892000-9ff4-11e9-93e5-12752b117fe3.png" width="200">


* 通常コメントとは表示を分ける
* 背景色は黄色（暖色）
  * 暗い色で心理的に暗いイメージを持たせたくない
* 各プライベートコメントの閲覧は以下のユーザのみ
  * 投稿したユーザ
  * 発表者
  * 管理者

## 検討事項

### 1. 管理者へのプライベートコメントの閲覧権限付与
→ イベントの方向性やアプリ改善のため、一旦権限ありとする
（将来的には、管理者の中でも権限を分けるか？）

### 2. “プライベートコメント”の名称
* 長い
* 硬い
* 直観的でない気がする
* でもいい案思いつかない。とりあえずこのまま？

**Comment by amderbar** [comment]
1. 管理者が閲覧できると何がうれしい？まさかりだった時に介入する？
2. 直感的でないという感覚がわからないが…一応案
    - ダイレクトコメント
    - ささやき
    - 非公開コメント

**Comment by Y-Kanoh** [comment]
> 1. 管理者が閲覧できると何がうれしい？まさかりだった時に介入する？

介入まではできないけど、アプリの仕様を変えるとか、何かしら手を打つことはできると思う。
全く見えなくすると、実際にどうやって使われているかがわからなくなり、効果があるのかもわからないし...

「プライベート（個人的な、私的な）コメント」というと、「本人と投稿者にのみ閲覧可能」という意味からずれてしまっている気がする。
上の案だと、「ダイレクトコメント」が一番しっくりきてます！

**Comment by skaji18** [comment]
> Spec2. プライベートコメント表示
> * 各プライベートコメントの閲覧は以下のユーザのみ
>   * 投稿したユーザ
>   * 発表者
>   * 管理者

プライベートコメントの運用次第でどうするか変わるので、質問です。  
プライベートコメントはコメント投稿者からの一方通行でしょうか？  
双方向にやり取りするのであれば、発表者側からのレスポンスが発表者と管理者しか閲覧できないように見えます。

**Comment by Y-Kanoh** [comment]
双方向については考えてなかった...。
投稿者の一方通行で考えていましたが、確かに発表者からのレスポンスは欲しいかも。

ただ、考えすぎかもしれないけど、レスポンスを返せることが、「アドバイスへの返答をしなければいけない義務感」になってしまうのは、心理的につらいかもしれないので避けたい。

実装の規模も大きくなってしまうため、一旦、一方通行で実装し、その後様子を見て双方向の実装を考える方向にしたいです。
