### ISSUE TITLE
アプリロゴの作成

### ISSUE THREAD

**Issue by amderbar** [rodbb/lambic#13]
アプリのロゴを作る
ホーム画面に表示させたりした時のアイコン、ファビコンも作る

**Comment by Nakano-Yusuke** [comment]
@amderbar @Y-Kanoh   
とても遅くなってしまいましたが、まずはファビコンを共有いたします。  
ビールの画像ですが、ファビコンサイズでも認識できると思うので問題ないかと思います。
↓
![favicon-16x16](https://user-images.githubusercontent.com/12774487/54070634-a6622e00-42a5-11e9-806a-bb4f6bacbe16.png)

よければ反映してみてください。

**Comment by Nakano-Yusuke** [comment]
アプリアイコンはzipで固めました↓ご査収ください 🙇 
* [ios-icons.zip](https://github.com/rodbb/lambic/files/2948321/ios-icons.zip)
* [android-icons.zip](https://github.com/rodbb/lambic/files/2948322/android-icons.zip)

**Comment by Nakano-Yusuke** [comment]
アプリロゴは↓こんな感じで。アプリアイコンからビールを差し引いただけです。
![logo](https://user-images.githubusercontent.com/12774487/54071085-58502900-42ab-11e9-9aed-7d34203f49ff.JPG)

**Comment by Nakano-Yusuke** [comment]
色々コメントしましたが↓で対応しました。
https://github.com/rodbb/lambic/pull/50
