### ISSUE TITLE
コメントのサブスクリーン表示

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#142]
# 概要
投稿されたコメントを、リアルタイムにサブスクリーンへ表示する

# 目的・背景
コメントの存在感が少なく、投稿数が伸びない。

# 提案内容
投稿されたコメントを目に見えやすい形で表示することで、コメントの存在感を上げる。

**Comment by skaji18** [comment]
> コメントの存在感が少なく、投稿数が伸びない。

利用者の意見であったのは、`発表中にコメント書くのが大変`というものです。  
これから考えると、コメントの存在感というより、気軽に投稿できるUIを考えるほうが効果的かもしれません。

とはいえ、いわゆる弾幕のようにコメントが表示されると盛り上がりやすいと思うので実装することに否はないです
