### ISSUE TITLE
発表以外にイベントに対してコメントがしたい

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#144]
# 概要
イベントに対するコメントを投稿できるようにする。

# 目的・背景
現状のコメントは、発表に対してのみのため、
イベントに対する手軽なコメントを行いたいとの要望があった。

**例**

* 食事に対する感想
* テーマに対する感想

# 提案内容
イベントに対してコメントを紐づけ、表示する。

**Comment by skaji18** [comment]
どう画面上で表現するかが問題になりそうです

また、反論する形になってしまいますが、現状でも運用でカバーできます
　発表を一つ作成し、そこでイベントに対するコメントを書いてもらう、など

対応するとしても、優先度は低めになると思います
