### ISSUE TITLE
READMEの更新

### ISSUE THREAD

**Issue by skaji18** [rodbb/lambic#152]
実装中に発見  
以下のコマンドを実行すると、非推奨メッセージが出る  
```bash
$ npx firebase list
This command is deprecated. Instead, use 'firebase projects:list' command to list your projects.
```

READMEの手順にあるコマンドなので修正が必要  
他のコマンドも同様のメッセージが出ないか確認し、あれば合わせて修正する

**Comment by amderbar** [comment]
確かに非推奨のメッセージは出るけれど、README.mdにそのコマンドは書かれていないのでクローズ
