### ISSUE TITLE
プロジェクトの方針相談

### ISSUE THREAD

**Issue by amderbar** [rodbb/lambic#166]
ビアバッシュの再開に向けて、Lambic もきれいに作り直したい。今のところ以下の変更を考えている。

* TypeScript への移行
  - 流行りの言語を使いたい
  - 静的型によってコードを分かりやすく変更しやすい状態にしたい
* Firebase をやめる
  - Firestore へのアクセス数問題が主な動機
  - スキーマレスなDBの扱いにくさというものもある

以下を相談したい。

* 上記変更の是非
* 変更するとしたらどうのようにするか
* 変更しないとしたら問題にどう対処するか（主に Firestore に関して）

**Comment by amderbar** [comment]
> TypeScript への移行

この場合、フロントエンドのライブラリもいっそ刷新してしまうかという話も出てくる。

* Vue.js を使い続けるか？ Vue 3 への移行もやっちゃうか？
  - 経験が仕事でも役立ちそう
  - 現状のコードを流用できるかも
* React に乗り換えてみるか？
  - 日本でも React が結構はやってきている
  - TypeScript との相性は Vue よりも良いと聞く

**Comment by amderbar** [comment]
> Firebase をやめる

Firebase をやめたとして、移行先はどうするか。立ち話のメモ。

* 予算がないので無料のクラウドサービスで何とかしたい
* サーバー側も自分で実装したほうがやりやすいのではないか
* Heroku を使うのはどうか
  * 常時稼働させておく必要がないので向いているかも
  * とはいえ Heroku でしか動かない状態は避けたい
  * docker コンテナで動かせるようにするといいのでは
* アプリの機能的に WebSocket 通信を使うことになる
  * Node.js か deno で Socket.IO を使うのがやりやすい
  * しかも全体を TypeScript で統一できる

**Comment by amderbar** [comment]
> Firebase をやめる

一方で認証関連については Firebase を使うことで大幅に省力化できている。Firebase をやめた場合、そこをどうするかも考えなおさないといけない。

**Comment by Y-Kanoh** [comment]
## Firebaseの使いどころ
* 認証は使っていい
* 無くてもよさげ
* 前の認証情報を引き継げる
* 認証処理は、他のライブラリもあるはず

→ 認証に他の手段があれば捨てる

## デプロイ環境
* Heroku
  * 無料
  * 時間制限はあるが、月一のビアバッシュ程度であれば問題ない
  * PostgreSQLの容量制限がある

### Herokuの容量制限回避策
* 過去のビアバッシュデータはエクスポートする
* エクスポートしたデータは削除できる
* エクスポートしたデータは GitHub pages で閲覧できる形式にしたい
  * コミットなどの操作はヒトが行う
  * あくまでLambicはエクスポートのみ
  * HTMLなどで出力できるようにする必要がある

## 使用言語は？
* Node.js使う
  * Web Socket 使いたい
  * TypeScript
  * JVM系はリソース食う


## フロントサイドは？
* React v.s. Vue.js
  * Lambic プロジェクトの意義を考えると "業務で使わない知識を選ぶ"べき
  * React の方が方針にあっているのでは？


## エクスポート機能
* Jamstack を使えば静的HTMLを簡単に作成可能
* OPEN API を作ってJSONを返すようにしておけばOK


# 結論
* Herokuにデプロイする方向で検討
  * サーバサイドも実装！
* 過去データはエクスポートできるようにする
* エクスポートしたデータは静的HTMLとして公開可能にする
* Firebaseは認証周りで必要なら使う
* TypeScript を Node.js で動かす
* React で。

**Comment by skaji18** [comment]
> エクスポート機能

* Jamstack の実現に Next.js を使うパターンの説明を見ると、 「Next.js 使えばできるよ」くらいの記述だった
    * https://jamstack.org/generators/next/
* Next.js について調べると、どうやらデフォルト機能で対応できる模様
    * https://nextjs.org/docs/advanced-features/static-html-export
    * > By default, `next export` will generate an `out` directory, which can be served by any static hosting service or CDN.

**Comment by skaji18** [comment]
優先度は低いが、MWアップデートはPR作成~マージまでを出来るだけ自動化したい

https://note.com/tabelog_frontend/n/nc52a54472e00

**Comment by amderbar** [comment]
github に組み込みの dependabot でも PR まではできるっぽい。

https://dev.classmethod.jp/articles/github-dependabot-2021/

**Comment by skaji18** [comment]
Renovate だと設定ファイルで自動マージの設定ができる模様。
https://blog.shibayu36.org/entry/2020/11/10/183000

dependabot では PR に特定のコメントをつければ良さそう。
とはいえ bot などで自動化しない場合は PR 画面を確認する必要があるので、結局手動でボタンを押すのと変わらない？

https://docs.github.com/ja/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/managing-pull-requests-for-dependency-updates
