### ISSUE TITLE
CI環境の整備

### ISSUE THREAD

**Issue by amderbar** [rodbb/lambic#19]
自動テストとデプロイの自動化

以下のコンポーネントはまずテストを書くところから

- [ ]  `App.vue`
- [ ]  `PresentasionDetail.vue`

**Comment by amderbar** [comment]
TravisCI or CircleCI
どっちがいいのかな？

**Comment by skaji18** [comment]
> 自動テスト

まずはE2Eテストで良いのでしょうか？  
個人的にユニットテストはなどか作ろうとしたのですが、vuex, vuexfireの絡みでうまくいかず頓挫しています...

**Comment by amderbar** [comment]
今 Circle CI を使っているけれど、外部サービスだとやっぱりわざわざそっちも見に行くのがちょっと面倒。

GitHub Actions に移行したい。

> 自動テスト

ユニットテストをぜひ充実させたいところ。それがやりにくいなら実装を見直したほうがいいのだろうね…。
