### ISSUE TITLE
コメントのマークダウン表記

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#20]
コメントをマークダウン表記で記述可能にする。

**Comment by Y-Kanoh** [comment]
追加情報をリンクで貼ったりして議論できることを目的とする

**Comment by amderbar** [comment]
XSSへの注意喚起
https://github.com/showdownjs/showdown/wiki/Markdown's-XSS-Vulnerability-(and-how-to-mitigate-it)

**Comment by skaji18** [comment]
https://github.com/anguer/vue-editor

こういうのもありますね
