### ISSUE TITLE
参加者用/エラーページの用意

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#25]
通信エラー時などが発生した場合に表示するエラーページを作成する

**Comment by amderbar** [comment]
リクエストされたプレゼンがない場合は404ページを表示したい。しかし c4ed30783b058ef23ce4a0d6af1ae37c49ab2863 で行ったLoadingの暫定対応ではpresentationデータを取得したときにそれが`null`だったらLoadingを出すとしたため、404を出すべきケースと区別できてない。
要修正

**Comment by amderbar** [comment]
参考
https://uyamazak.hatenablog.com/entry/2018/05/28/190513

**Comment by Y-Kanoh** [comment]
現状、この問題が生じているのは、イベント一覧ページだけの認識だけどあってる？？

**Comment by amderbar** [comment]
ログイン以外の全部のページに亘って発生している認識。ローディングを表示している個所はすべてその問題を抱えていそう。
