### ISSUE TITLE
ログインユーザ情報表示/編集画面

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#28]
サイドメニューに追加する

- [x] ユーザーのプロフィール画像を表示する（匿名の場合はデフォルト画像）
- [x] ユーザーの名前を表示する
- [ ] ユーザーの名前を変更できるようにする
- [x] 以上は発表詳細のコメントにも反映する
- [ ] 管理者ユーザフラグを持たせる

**Comment by amderbar** [comment]
@Y-Kanoh @Nakano-Yusuke `yeast`の段階でこの機能必要？
必要なら画面デザインを相談したいです。

**Comment by Y-Kanoh** [comment]
<img src="https://user-images.githubusercontent.com/12679843/53814060-4bc58b00-3fa2-11e9-88e0-cef10b281b57.png" width="400">

そもそも、ログインユーザとその他ユーザでどこまで機能を制限する？？

外部の人も使うことを想定すれば、

* 発表登録のみログインが必要
* そのほかの機能は「ゲストユーザ」として利用可能（コメントなど）

目的によっては、「発表情報の閲覧」「コメントの投稿」もログイン必須にしてもよい。

**Comment by amderbar** [comment]
ログイン機能に関して相談の必要がありそうなのでいったん`yeast`から外します。
