### ISSUE TITLE
Vuexの警告

### ISSUE THREAD

**Issue by amderbar** [rodbb/lambic#31]
Vuexfireを使っていると、Vuexをstrictで動かしたときに警告が出てくる。どうにかしたい。最悪Vuexfireの使用をやめることも検討

refs #26

**Comment by amderbar** [comment]
Reference型のデータは、基本的にオブジェクトとして取得されるのだが、たまにリファレンス文字列のままになっていることがある。
そのせいでコメントを投稿したときに、コメントの投稿者が正しく表示されないことがある

**Comment by Y-Kanoh** [comment]
https://vuefire.vuejs.org/vuexfire/

一応読んでみる

**Comment by Y-Kanoh** [comment]
原因と解決方法の考察
======================

## 事象

生じているエラーは以下の2種類。両方とも。以下の文言がある。

> Error: [vuex] do not mutate vuex store state outside mutation handlers.
（ vuex store state を mutation ハンドラの外で変更したらはあかんで。）

![image](https://user-images.githubusercontent.com/12679843/56465772-91e68900-6440-11e9-8544-52701245f4fe.png)


## 原因

`sort()`メソッドは、元の配列の順番を変更してしまうため、store state の値を変更したことになっていた。

## 修正方法

store state から配列をコピーしてからソートするように変更する。

## 調査履歴

### エラー箇所の予想

一つ目のエラーの詳細を確認すると、一番最初に出てくる自作のファイルが store.js で、その中の `comments` に関するところでエラーが発生していることが分かった。
二つ目のエラーも同様。

![image](https://user-images.githubusercontent.com/12679843/56465837-fce48f80-6441-11e9-88ad-1c500dc38824.png)
![image](https://user-images.githubusercontent.com/12679843/56465856-5220a100-6442-11e9-8b18-464e92a8df1d.png)

### 原因の考察

store.js のエラー発生個所は以下の通り。
（`comments`の getter）
```JS
    comments (state) {
      return state.comments
        .sort((a, b) => {
          // 投稿日時の昇順にソート
          const dsec = a.postedAt.seconds - b.postedAt.seconds
          const dnanosec = a.postedAt.nanoseconds - b.postedAt.nanoseconds
          return dsec === 0 ? (dnanosec > 0) - (dnanosec < 0) : (dsec > 0) - (dsec < 0)
        })
    },
```

`sort()` メソッドを外したらエラーが出なくなった。
しかし、`events`の getter のような、他のメソッドで`sort()`メソッドを使用しているところではエラーが出ていない。

`events`の getter と、`comments`の getter との大きな違いは、`map()`メソッドを使った後に`sort()`メソッドを使っているかなので、`map()`メソッドと`sort()`メソッドのリファレンスを比較。

![image](https://user-images.githubusercontent.com/12679843/56465959-230b2f00-6444-11e9-933a-b32961e2a4de.png)

`map()`メソッドは、元となる配列から新しい配列を作って返す。
それに対し、`sort()`メソッドは、元の配列 を編集してしまう。

今回は、元の配列 ＝ store state なので、store state を mutation の外で変更したことになりエラーになる。

実際に、`comments `の getter に`map()`メソッドを挟んだら解消した。

**Comment by amderbar** [comment]
そういうことだったのか…。てっきりVuexfireのせいかと。思いっきり私のせいじゃないか…。
調査ありがとう。しりぬぐいさせてしまって申し訳ない。

**Comment by Y-Kanoh** [comment]
いやいや、勉強になった！
これはQiitaネタぐらいにはなるで。
（あわよくばTechブログ...）

**Comment by amderbar** [comment]
これ解決したんじゃなかったっけ。
閉じておきますね。
