### ISSUE TITLE
発表登録ができない

### ISSUE THREAD

**Issue by amderbar** [rodbb/lambic#34]
ログイン機能が無い現段階では発表者をreference型にしていると正しく発表者の登録ができない。

* しばらくの間はusersコレクションにダミーのuidで発表者を登録する？
* 発表者を文字列型で登録できるようにする？

**Comment by amderbar** [comment]
@Y-Kanoh @Nakano-Yusuke とりあえずこっちの運用にすることにしたいと思うけどいかがか？

> しばらくの間はusersコレクションにダミーのuidで発表者を登録する？

後からデータ型を変更した場合、アプリ内でデータ型が違うことがあることを考慮した実装にしなければならなくなりそう。できればデータ型を途中で変えたくはない

**Comment by Y-Kanoh** [comment]
ダミーのuidというのは、ユーザドキュメントのIDのこと？
手動でドキュメントIDを作成するイメージであってる？？

![image](https://user-images.githubusercontent.com/12679843/53736523-55c98a00-3ecd-11e9-85bf-64eea0e18332.png)

**Comment by amderbar** [comment]
そうです。
今は匿名認証で発行されたuidをドキュメントのIDにしてユーザーを登録しています。
現状では発表者のuidが不明なので、発表者の登録するときはダミーのドキュメントIDでデータを登録しておくようにしようかって案です。

**Comment by Y-Kanoh** [comment]
運用としてはこんなイメージであってる？

発表希望者のみユーザ登録
（手動割り振りドキュメントID）
　↓
登録したユーザに紐づいたプレゼンを登録

* 発表者以外はゲストユーザで利用
* 発表者も閲覧時はゲストユーザで利用

**Comment by amderbar** [comment]
利用者のログイン機能が実装されているのでclose
