### ISSUE TITLE
発表順の考慮

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#36]
発表順でソートする考慮がない

**Comment by amderbar** [comment]
発表枠の区別もない

**Comment by Y-Kanoh** [comment]
以下の3つを追加することで解消する？

1. presentationドキュメント -> ソート番号
2. presentationドキュメント -> 発表枠識別子
3. 発表枠識別子 管理コレクション（LT枠/テーマ枠 以外の枠が増えることを考慮）
