### ISSUE TITLE
QRコードのタイトルが欲しい。

### ISSUE THREAD

**Issue by amderbar** [rodbb/lambic#38]
サイドメニューQRコードのタイトルが欲しい。
「共有」のためのQRコードがわかる文言が欲しい。
（ロゴやユーザ情報参照などの、サイドメニュー機能追加の時でもいいかな。）

_Originally posted by @Y-Kanoh in https://github.com/rodbb/lambic/pull/30#issuecomment-466660401_

**Comment by Y-Kanoh** [comment]
![image](https://user-images.githubusercontent.com/12679843/53812249-6eee3b80-3f9e-11e9-98ae-49caeab8966a.png)
こんなのはどうだろう
