### ISSUE TITLE
参加者用/コメント投稿機能

### ISSUE THREAD

**Issue by amderbar** [rodbb/lambic#4]
選択した発表へのコメントを投稿できるようにする

- [x] 選択した発表の詳細表示画面
- [x] コメント入力モーダルの表示
- [x] コメントをstoreに反映

**Comment by Y-Kanoh** [comment]
必要なバリデーション
* 長さ
* 空文字チェック
* スペースのみチェック

**Comment by amderbar** [comment]
テストしにくくなってしまった感…。
