### ISSUE TITLE
翻訳ダイアログの表示防止

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#42]
Chromeで画面を開いた時、Google翻訳するかを問うダイアログが表示されるため、
ページの言語を変更する。
![capture](https://user-images.githubusercontent.com/12679843/53697777-2ad12e80-3e18-11e9-834f-f0f9fc3cd0e3.png)

**Comment by amderbar** [comment]
最初に作ったときからその辺まったく気にしてなかった。
Thunks!
