### ISSUE TITLE
サブスクリーンの実装

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#54]
表示するスタンプと機能の概要については #53 を参照。

## タスク詳細
- [x] 管理画面の作成
- [x] サブスクリーンの作成

## 管理画面の作成
![capture1](https://user-images.githubusercontent.com/12679843/56088190-a235bb80-5eb6-11e9-9b20-5a3a3c15a3b9.png)

管理画面からプレゼンが選択されると、DBの「サブモニタ管理ドキュメント」が変更されて、表示される画面が変わるイメージ。
（ほかのいい実装方法があったら提案して）

## サブスクリーンの作成
* DBのスタンプカウント数が増えたら、表示しているスタンプが一瞬点灯する
* スタンプだけでは味気ない & どのプレゼンかわからないから、画面にプレゼン名ぐらい表示する？

将来的には、複数会場での開催を想定し、スクリーンが複数用意できるようにする。
コレクションとして「screens」を用意し、スクリーン用URLにアクセスしたら、「screens」コレクションのドキュメントに記載されたプレゼンテーションIDに対するリアクションを表示する

### 「screens」コレクション
* name：スクリーン名を入れる
* presentationId：プレゼンテーションID

**Comment by amderbar** [comment]
サブスクリーン側の実装に使えるかも

https://qiita.com/Niemuuu/items/5dde43b4e7e6f3dc5cf4

**Comment by amderbar** [comment]
`feat/subscreen`ブランチ作りました

**Comment by Y-Kanoh** [comment]
サブスクリーン管理画面の実装をしたら、`feat/subscreen` にプルリク出せばよい？？

**Comment by amderbar** [comment]
サブスクリーンの画面デザインはどうすればよいかな？

**Comment by Y-Kanoh** [comment]
今、速攻で考えたデザイン

![image](https://user-images.githubusercontent.com/12679843/56458698-0f6cb380-63c5-11e9-8934-9e2a60643696.png)

**Comment by Y-Kanoh** [comment]
以下の情報は載せる。

* 発表タイトル
  今どの発表のリアクションが表示されてるか判断するため
* スクリーン名（会場名？）
  どの会場向けスクリーンが表示されているかわからなくなるため
* スタンプ
