### ISSUE TITLE
未ログインユーザコメント投稿時のログイン画面遷移

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#61]
未ログインユーザがコメントを投稿しようとしたときに、
ログイン画面へ誘導したい。

投稿時には、ログインユーザの名前やPhotoUrlが必要なので、未ログインユーザはログイン画面へ誘導したい。

**Comment by Y-Kanoh** [comment]
案をA～Cまで出すので、どれがいいか月曜までに選んでほしいです。
いいと思った案には絵文字でリアクションお願いしたいです。

期限：4/22まで

![image](https://user-images.githubusercontent.com/12679843/56450726-f0d5d080-6362-11e9-8432-f530d7c70039.png)

**Comment by Y-Kanoh** [comment]
## 案Ａ

投稿ダイアログを開くことなくログイン画面へ遷移。

「鉛筆マーク」が「投稿」を意味することをユーザが知っている必要があるので、
ユーザによっては「何かわからないボタンを押したらログイン画面へ飛ばされた」と感じる気がする。

![image](https://user-images.githubusercontent.com/12679843/56450985-6bebb680-6364-11e9-9509-7e758e87529b.png)

**Comment by Y-Kanoh** [comment]
## 案B

SUBMIT時にログイン画面へ。
ユーザはすでにコメントを入力しているので、ログイン後にコメント入力画面まで戻って入力済みの文字を表示する必要がある。
実装コストは少し高いかも

![image](https://user-images.githubusercontent.com/12679843/56451012-950c4700-6364-11e9-9064-a91094db5940.png)

**Comment by Y-Kanoh** [comment]
## 案C

ダイアログに入力できない旨を表示して、ログイン画面へのボタンを作る。
入力はできないように、テキストエリアは非活性

![image](https://user-images.githubusercontent.com/12679843/56451019-a2c1cc80-6364-11e9-8c33-4593ef3459ff.png)

**Comment by amderbar** [comment]
例えばqiitaだと、ログインしていない状態ではコメント投稿のUIがなくて、代わりにユーザー登録とログイン画面への誘導がある。
![image](https://user-images.githubusercontent.com/12950005/56451229-b588d100-6365-11e9-938e-fc369f342cae.png)

いいねをしようとすると、モーダルでこれとほぼ同じものが出るね。この点は案Aに近いかも。

**Comment by Y-Kanoh** [comment]
> 例えばqiitaだと、ログインしていない状態ではコメント投稿のUIがなくて、代わりにユーザー登録とログイン画面への誘導がある。
> ![image](https://user-images.githubusercontent.com/12950005/56451229-b588d100-6365-11e9-938e-fc369f342cae.png)
> 
> いいねをしようとすると、モーダルでこれとほぼ同じものが出るね。

これいいね。
案Cのモーダルを、わざわざ投稿処理と同じ形にする必要ないわけだし。

**Comment by skaji18** [comment]
一点だけ、`FB希望制御`機能における「コメントできない表示」との違いが分かるようになっているか、という点には気を付けておきたいです。  
案Cのように「ログインしてね」メッセージがモーダル内で表示されるなら気にしなくて大丈夫ですが。。。

**Comment by Y-Kanoh** [comment]
一番得票が多かった「[案C](https://github.com/rodbb/lambic/issues/61#issuecomment-485053728)」にしましょう！

**Comment by Y-Kanoh** [comment]
ログイン促す画面イメージ

![image](https://user-images.githubusercontent.com/12679843/56906646-a8927d00-6add-11e9-95aa-8ff4e5414d6f.png)

**Comment by Nakano-Yusuke** [comment]
#77 で対応いたしましたのでクローズします。
