### ISSUE TITLE
画面リロード時のアラート

### ISSUE THREAD

**Issue by amderbar** [rodbb/lambic#62]
#56 の修正による影響？

![image](https://user-images.githubusercontent.com/12950005/56450740-106cf900-6363-11e9-857c-1417c286ddab.png)

**Comment by Y-Kanoh** [comment]
申し訳ない。おそらくこれが原因。

![image](https://user-images.githubusercontent.com/12679843/56451318-25975700-6366-11e9-9034-8270c1b8baaa.png)

#59 にて、匿名認証をなくしたので、実装時に Firebase で匿名認証を許可しない設定にしたままでした。
これにより、認証エラーになっていたようです。

一旦、匿名認証を許可しました。#59 がマージされたタイミングで設定しなおします。

**Comment by amderbar** [comment]
subscreenの実装で匿名認証復活させるかも

**Comment by Y-Kanoh** [comment]
マジか。

**Comment by Y-Kanoh** [comment]
そうなったら復活させよ。
設定は許可のままにしておきます。

**Comment by Y-Kanoh** [comment]
問題は解消しているためクローズ
