### ISSUE TITLE
コメント表示のデザイン修正

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#63]
![image](https://user-images.githubusercontent.com/12679843/56451857-c4bd4e00-6368-11e9-9892-697739cbdc2f.png)

1. 投稿ユーザ名をもう少し小さく。長すぎる場合は`...`を表示できたらGoog。
2. 時間表示は年月日時分までに。

2は EventList.vue でも使ってる `moment` を使えそう。
1は [vuetify](https://vuetifyjs.com/en/components/lists) で頑張る

**Comment by amderbar** [comment]
これ`invalid`なのか？
> This doesn't seem right
「これ（このissue）は正しくないようです」？

**Comment by Y-Kanoh** [comment]
`invalid` ではないね。修正します。分類的にはバグかな？

**Comment by amderbar** [comment]
`invalid`の使いどころがいまいちわからない…。issueを上げるひとが増えてくると使うこともあるのかな

**Comment by Nakano-Yusuke** [comment]
#65 で対応いたしましたのでクローズします。
