### ISSUE TITLE
FireStoreへのアクセス数削減

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#68]
現状出ている案

* キャッシュを使う
* 取得時に必ずフィルタで絞り込む
* FireStoreでのデータの持ち方を変える
  * リファレンスで他ドキュメントの参照をやめる
  * すべてサブコレクションで実装する

**Comment by skaji18** [comment]
念のため共有。  

オフラインデータの有効化  
https://qiita.com//Bosch_san/items/e3e06acdb3c7b53553f2  

※マルチタブ対応の書き方が[Version 6.0.0](https://firebase.google.com/support/release-notes/js?hl=ja#version_600_-_may_7_2019)  では変わってるようです。  
https://firebase.google.cn/docs/reference/js/firebase.firestore.PersistenceSettings#optionalsynchronizetabs

**Comment by Y-Kanoh** [comment]
内容が多いので分割する！

**Comment by Y-Kanoh** [comment]
以下のようにすすめようと思ってるんだけど、問題ないよね？？

プルリク内の変更箇所が多くなるので、**ドキュメントの取得方法変更** にて変更する各ドキュメントごとの実装と、**キャッシュの使用** とでプルリクを分けようと思っています。

## 1. 各ドキュメントの取得方法変更
単体のドキュメントを読み取るときに、コレクションをすべて読み取った配列から、対象のドキュメントを取得する処理を廃止。
毎回firebaseから読み取るように変更する。

- [ ] presentations
- [ ] comments
- [ ] events
- [ ] screens
- [ ] stampCounts

## 2. キャッシュを使うように変更

キャッシュの設計等考慮事項は多そう。
