### ISSUE TITLE
参加者用/参加登録機能

### ISSUE THREAD

**Issue by amderbar** [rodbb/lambic#7]
未開催のビアバッシュに対して参加者登録をできるようにする
その際、参加枠を選べるようにする

* オーディエンス参加
* テーマ枠発表
* 自由枠発表
* LT枠発表

**Comment by Y-Kanoh** [comment]
参加したイベントには、マークをつけておきたい。
(オーディエンス参加ならオーディエンスアイコン、発表参加なら発表アイコンなど)

**Comment by Y-Kanoh** [comment]
画面案。
意見欲しいです！

<img src="https://user-images.githubusercontent.com/12679843/53893768-33bd3c80-4072-11e9-8800-5aa19048e7cb.png" width="300">

ボタンを付けるにあたって、説明文があると長すぎるので、畳んでみようかと。

<img src="https://user-images.githubusercontent.com/12679843/53893946-8c8cd500-4072-11e9-96de-efb6512d5b71.png" width="150">
