### ISSUE TITLE
ログアウト状態でプログレスバーが表示され続ける

### ISSUE THREAD

**Issue by Nakano-Yusuke** [rodbb/lambic#73]
■関連
* Isuue #32 
* PR #72 

■事象
* firestoreのルール設定に伴い、ログアウト状態で読み取り不可にした場合、画面にプログレスバーが表示され続ける

<img src="https://user-images.githubusercontent.com/12774487/56858945-ed26f700-69bd-11e9-9fa1-611a05a1b896.gif" width="320px">

**Comment by Nakano-Yusuke** [comment]
この手の問題はルールを拡張していくといっぱい出てきそうです（まずはルールのFixを急ぎます！）。

**Comment by Y-Kanoh** [comment]
セキュリティルールをちゃんとしたら解決
