### ISSUE TITLE
コメントのアバターにphotoURLの画像を使っていない

### ISSUE THREAD

**Issue by skaji18** [rodbb/lambic#75]
コメントのアバターが常に黒丸  
photoURLの画像を表示したい

![022995D4-E051-4F23-A095-7CAF8DF6A09B](https://user-images.githubusercontent.com/18644766/56908679-bea23c80-6ae1-11e9-95ec-ded798c7168a.jpeg)

**Comment by Nakano-Yusuke** [comment]
こんな感じでできそうなのでやってみます。

<img width="881" alt="スクリーンショット 2019-04-30 14 03 32" src="https://user-images.githubusercontent.com/12774487/56941676-f4323e80-6b50-11e9-946b-b5cb0d0b5284.png">
<img width="815" alt="スクリーンショット 2019-04-30 14 04 33" src="https://user-images.githubusercontent.com/12774487/56941678-f5636b80-6b50-11e9-8032-4f81c56566d1.png">

**Comment by Nakano-Yusuke** [comment]
なぜか私は名前が表示されないというイジメに合ってます。。

**Comment by Nakano-Yusuke** [comment]
#78 で対応いたしましたのでクローズします。
