### ISSUE TITLE
画面サイズが小さい時にナビゲーションが非常に閉じにくい

### ISSUE THREAD

**Issue by skaji18** [rodbb/lambic#80]
![image](https://user-images.githubusercontent.com/18644766/57005292-da0c6500-6c11-11e9-95f5-996cee2d1e36.png)

**Comment by skaji18** [comment]
iPhone5/SEだとほぼ埋まってしまう。。。

**Comment by Y-Kanoh** [comment]
実機では、スワイプで閉じれることが分かったので、クローズします。
