### ISSUE TITLE
一覧表示系の画面で最後の行がdividerで終わっている

### ISSUE THREAD

**Issue by skaji18** [rodbb/lambic#81]
dividerはコンテンツを区切る線なので、最後についているのは違和感を感じる

![0F4383BF-72F8-4C4B-911B-204855D4F369](https://user-images.githubusercontent.com/18644766/57015157-3beac000-6c4e-11e9-8f80-24545503cc37.jpeg)

**Comment by Y-Kanoh** [comment]
これ、なんかスマートな解決方法ないかな？

**Comment by skaji18** [comment]
パッと探して見つかったやつです

https://stackoverflow.com/questions/42129534/vuejs-how-to-output-a-comma-separated-array
![8959D02A-169C-481A-ACF8-840DA1DB3EFB](https://user-images.githubusercontent.com/18644766/57053288-f965c980-6cc7-11e9-8abb-f6ac26aba2b5.jpeg)
