### ISSUE TITLE
スタンプの決定

### ISSUE THREAD

**Issue by Y-Kanoh** [rodbb/lambic#86]
そろそろスタンプの画像を決めないといけない。

候補をここに出してほしいです！

* 画像がなければ文字だけでも可（採用決定後画像を作成）

※ 今週中（5/11 土 まで）にお願いしたいです。

**Comment by Y-Kanoh** [comment]
* ナルホド
* イイネ
* www（読みは「ワラワラ」？）

**Comment by skaji18** [comment]
おススメです  
参照元:GitHub

![5D2A1E19-ADF8-490D-BCF6-E4A976D7884E](https://user-images.githubusercontent.com/18644766/57337778-bc855100-7165-11e9-82b2-442137169921.jpeg)

**Comment by Y-Kanoh** [comment]
上記案から、以下の内容でどう？？

|タイトル|アイコンイメージ|
|--|--|
|いいね|:+1:|
|ナルホド|4文字 MMostにあるアイコンのような|
|笑い|「笑」の一文字 or 😆 |

**Comment by Y-Kanoh** [comment]
<img src="https://user-images.githubusercontent.com/12679843/57978993-0c132900-7a52-11e9-943e-04aae11d790c.png" width="100">
<img src="https://user-images.githubusercontent.com/12679843/57978999-2816ca80-7a52-11e9-9173-21b100901e63.png" width="100">
<img src="https://user-images.githubusercontent.com/12679843/57979001-2fd66f00-7a52-11e9-9581-2cdd1dee970c.png" width="100">

**Comment by skaji18** [comment]
メモ、firebase storageからの画像取得を高速化  
https://techlife.cookpad.com/entry/2018/11/02/100000
