### ISSUE TITLE
イベント詳細画面でF5で画面再読み込みするとJSエラーが発生する

### ISSUE THREAD

**Issue by skaji18** [rodbb/lambic#89]
いつから発生していたのかは不明（もしかすると最初から...?）

![image](https://user-images.githubusercontent.com/18644766/57577107-d34fde80-74aa-11e9-9667-d94428e8647e.png)

**Comment by skaji18** [comment]
再読み込みでは、データの読み込みより早く処理が始まってしまうことが原因か

**Comment by amderbar** [comment]
手元では再現しない。
今でも再現する？ 再現するなら調査頼みます。

**Comment by skaji18** [comment]
日付変換処理の対応で直っているようです。  
`pr.date.seconds`のような書き方をしている場合に、データの読み込みと処理のタイミングで`date`が`undefined`になってしまう場面がありました。この時に`date.seconds`  プロパティを参照することでエラーが発生していたようです。  
修正により`date.seconds`プロパティを参照しなくなったため、エラーが発生しなくなっているようです。

https://github.com/rodbb/lambic/commit/00249c2747c4d2a331b0223483b2667bd469f48e#diff-c1776b089c267ce3df955babfed54e6aL51
